version: 2

# global environment variables
env-shared: &env-shared
  environment:
    GOFLAGS: ""

# build steps shared across different jobs
build-shared: &build-shared
  steps:
    - checkout
    - run:
        name: Run gofmt -s
        command: |
          if [ $(find . -name "*.go" -exec gofmt -s -d {} \;|wc -l) -gt 0 ]; then
           find . -name "*.go" -exec gofmt -s -d {} \;
           exit 1;
          fi
    - restore_cache:
        keys:
          - pkg-cache-{{ checksum "go.sum" }}-v6
    - run:
        name: Download dependencies
        command: go mod download
    - run:
        name: Run tests
        command: |
          go test -v ./...
    - run:
        name: Get gox
        command: |
          go install github.com/mitchellh/gox@latest
    - run:
        name: Compile project on every platform
        command: |
          gox -parallel 10 -os "linux freebsd" -osarch "darwin/amd64 darwin/arm64 windows/amd64"
    - save_cache:
        key: pkg-cache-{{ checksum "go.sum" }}-v6
        paths:
          - ~/.cache/go-build
          - /go/pkg/mod

jobs:
  "golang:1.24":
    <<: *env-shared
    <<: *build-shared
    docker:
      - image: cimg/go:1.24
  "golang:latest":
    <<: *env-shared
    <<: *build-shared
    docker:
      - image: cimg/go:1.25
  release:
    <<: *env-shared
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - run:
          name: Run gorelease
          command: |
            curl -sL https://git.io/goreleaser | bash
      - run:
          name: Update docs
          command: |
            ./.circleci/update_docs.sh

workflows:
  version: 2
  build:
    jobs:
      - "golang:1.24"
      - "golang:latest"
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
